music_directory "~/Music"
playlist_directory "$XDG_CONFIG_HOME/mpd/playlists"
db_file "$XDG_CONFIG_HOME/mpd/database"
pid_file "$XDG_CONFIG_HOME/mpd/pid"
sticker_file "$XDG_CONFIG_HOME/mpd/sticker.sql"
log_file "$XDG_CONFIG_HOME/mpd/log"
state_file "$XDG_CONFIG_HOME/mpd/state"

bind_to_address "localhost"
port "6600"

audio_output {
  type "pipewire"
  name "PipeWire Output"
}
